# The `FROM` instruction specifies the base image. You are
# extending the `microsoft/aspnet` image.

https://access.redhat.com/RegistryAuthentication

# The final instruction copies the site you published earlier into the container.
COPY ./bin/Release/PublishOutput/ /inetpub/wwwroot
